### ISSUE TITLE
Perlimports not detecting local package

### ISSUE THREAD

**Issue by Vic-M** [perl-ide/App-perlimports#103] opened 2023-09-01 19:01 UTC
Perl imports doesn't seem able to pick my local packages and always recommends removing them.

![image](https://github.com/bscan/PerlNavigator/assets/32042587/436f2a8f-502f-4787-ab67-75c2c1e29a74)

reference code: https://gitlab.com/vmatassa/perl_import_test

For context, I'm running perlimports through Perl-navigator (bscan/PerlNavigator#86)

perl version: v5.32.1
perl navigator version: 0.5.9
App::perlimports version: 0.000052

**Comment by oalders** [comment] 2023-09-01 22:38
Thanks for making this reproducible. I think part of the issue is that you need the fully qualified package names in the packages themselves.

```diff
git diff
diff --git a/script.pl b/script.pl
index 31441ce..3622602 100644
--- a/script.pl
+++ b/script.pl
@@ -7,5 +7,5 @@ use FindBin::libs qw(base=src);
 use MyProject::PackageB qw(someOtherFunc);
 use MyProject::PackageA;

-say PackageA::someFunc();
+say MyProject::PackageA::someFunc();
 say someOtherFunc();
diff --git a/src/MyProject/PackageA.pm b/src/MyProject/PackageA.pm
index 25f24d4..a7f0311 100644
--- a/src/MyProject/PackageA.pm
+++ b/src/MyProject/PackageA.pm
@@ -1,6 +1,6 @@
 #!/usr/bin/perl

-package PackageA;
+package MyProject::PackageA;

 use strict;
 use v5.26;
diff --git a/src/MyProject/PackageB.pm b/src/MyProject/PackageB.pm
old mode 100644
new mode 100755
index 2a4bf59..a14dce4
--- a/src/MyProject/PackageB.pm
+++ b/src/MyProject/PackageB.pm
@@ -1,6 +1,6 @@
 #!/usr/bin/perl

-package PackageB;
+package MyProject::PackageB;

 use strict;
 use v5.26;
```

Now I get:

```
perlimports --lint script.pl
❌ MyProject::PackageB (appears to be unused and should be removed) at script.pl line 7
@@ -7 +6,0 @@
-use MyProject::PackageB qw(someOtherFunc);

❌ MyProject::PackageA (import arguments need tidying) at script.pl line 8
@@ -8 +8 @@
-use MyProject::PackageA;
+use MyProject::PackageA ();
```

I think this is correct because you're not importing any symbols from `MyProject::PackageA` and  since `someOtherFunc` doesn't exist in `MyProject::PackageB`, nothing is being imported from it and it's not being used with a fully qualified function call.

**Comment by Vic-M** [comment] 2023-09-02 00:09
My mistake, didn't double check while copy pasting... I have updated the code.

![image](https://github.com/perl-ide/App-perlimports/assets/32042587/7e8ee831-a680-4b1c-b4d2-f50ce4596ceb)


After some research, my first mistake was writing `package PackageB` instead of `package MyProject::PackageB` as is the perl convention. However, in my actual codebase, I don't usually export anything but rather just use the package itself in shorthand notation like 
```
say PackageA::someFunc();
#say MyProject::PackageA::somFunc(); #full package name too long
```

However perlimports doesn't recognize that `PackageA` is being used in this case.

**Comment by oalders** [comment] 2023-09-03 18:52
I believe that if you'd need to change `say PackageA::someFunc()` to `say MyProject::PackageA::someFunc()` so that `perlimports` knows you're referring to the same package.

**Comment by Vic-M** [comment] 2023-09-04 04:53
Unfortunately, that's what I'm trying to avoid in this case. Would it possible to add support for partial namespaces? If not, we can close this issue. Thanks.

**Comment by oalders** [comment] 2023-09-04 15:37
`perlimports` is trying to make it easier to enforce best practices, but I don't think I would file this under best practice. What's the problem that you're trying to solve?

**Comment by Vic-M** [comment] 2023-09-04 18:50
`perlimports` doesn't recognize packages when not using a package's fully qualified name. If I have a package `Some::Really::Long::PackageName` and use it in my code as `PackageName::someFunc()`, `perlimports` can see the package (ie that it exists) but can't detect that it's being used in the code. Ideally, it would be able to detect which packages are being used without specifying the fully qualified name in the package file itself.

**Comment by oalders** [comment] 2023-09-04 19:46
The traditional solution to not wanting to type long package names to get at a function would be to make the functions exportable and them import them. That would fit within the scope of `perlimports` already is set up to do. There's also stuff like https://metacpan.org/pod/namespace::alias

At any rate, I think this request is outside of the scope of `perlimports`, so I'm going to close it, but I appreciate you bringing it to my attention.

**Closed by oalders** 2023-09-04 19:46 UTC
